# example netlify.toml
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "./"



  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection


  ## more info on configuring this file: https://docs.netlify.com/configure-builds/file-based-configuration/
[dev]
   command = "npm start" # Command to start your dev server
   port = 5800 # Port that the dev server will be listening on
   publish = "dist" # Folder with the static content for _redirect file
